header:
  license:
    spdx-id: MIT
    copyright-owner: Facebook
    content: |
      Copyright (c) Facebook, Inc. and its affiliates.

      This source code is licensed under the MIT license found in the
      LICENSE file in the root directory of this source tree.
      
  paths: # `paths` are the path list that will be checked (and fixed) by license-eye, default is ['**'].
    - '/src'

  paths-ignore: # `paths-ignore` are the path list that will be ignored by license-eye.
    - '.dependabot'
    - '.github'
    - 'dist'
    - 'rss'
    - 'templates'

    - 'LICENSE'
    - 'NOTICE'
    - '.editorconfig'
    - '.eslintignore'
    - '.gitattributes'
    - '.gitignore'
    - '.node-inspectorrc'
    - '.prettierignore'
    - '.vimrc'
    - '.whitesource'
    - 'rust_toolchain'

    - '**/*.md'
    - '**/*.lock'
    - '**/*.yaml'
    - '**/*.yml'
    - '**/*.json'
    - '**/*.toml'
    - '**/*.svg'
    - '**/*.js'

  comment: on-failure
