header:
  license:
    spdx-id: MIT
    copyright-owner: Facebook
    content: |
      Copyright (c) Facebook, Inc. and its affiliates.

      This source code is licensed under the MIT license found in the
      LICENSE file in the root directory of this source tree.

  comment: on-failure
