[package]
name = "binutils"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tail"
path = "src/bin/tail.rs"

[dependencies]
anyhow = "1.0"
structopt = "0.3"
thiserror = "1.0.30"
itertools = "0.10.3"