[package]
name = "binutils"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "uniq"
path = "src/bin/uniq.rs"

[dependencies]
anyhow = "1.0"
structopt = "0.3"
thiserror = "1.0"
itertools = "0.10"

[dev-dependencies]
pretty_assertions = "1.0"
test-generator = "0.3"