imports_granularity = "Crate"
wrap_comments = true
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
