
on:
  push:
    branches:
    - main
    
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  add_header:
    name: Adds licenses to headers
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Fix License Header
      uses: apache/skywalking-eyes@main
      with:
        mode: fix

    - name: Apply Changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: License Bot
        author_email: license_bot@github.com
        message: 'Automatic application of license header'
