
on:
  push:
    branches:
    - main

jobs:
  add_header:
    name: Adds licenses to headers
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Fix License Header
      uses: apache/skywalking-eyes@main
      with:
        mode: fix
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
