- name: Fix License Header
  uses: apache/skywalking-eyes@main
    with:
      mode: fix
- name: Apply Changes
  uses: EndBug/add-and-commit@v4
    with:
      author_name: License Bot
      author_email: license_bot@github.com
      message: 'Automatic application of license header'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
