name: Header Comments CI
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Add comments
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Add comments to src/
        uses: koj-co/header-comments@v1.0.5
        with:
          directory: '**/src'
      - name: Create commit with changes
        uses: stefanzweifel/git-auto-commit-action@v4
